### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Shurtu-gal**

### CODE REVIEW

**Comment by ash17290** [comment]
@ash17290 I don't have permissions to update this PR. Please ask the PR author to check the "Allow edits from maintainers" checkbox in the PR settings.

**Comment by ash17290** [comment]
@ash17290 I don't have permissions to update this PR. Please ask the PR author to check the "Allow edits from maintainers" checkbox in the PR settings.

**Comment by ash17290** [comment]
@ash17290 I don't have permissions to update this PR. Please ask the PR author to check the "Allow edits from maintainers" checkbox in the PR settings.

**Comment by ash17290** [comment]
@ash17290 I don't have permissions to update this PR. Please ask the PR author to check the "Allow edits from maintainers" checkbox in the PR settings.

**Comment by ash17290** [comment]
@ash17290 I don't have permissions to update this PR. Please ask the PR author to check the "Allow edits from maintainers" checkbox in the PR settings.

**Comment by ash17290** [comment]
@ash17290 The updation of PR has failed. It can be due to one of the following reasons:
    - I don't have permissions to update this PR. To update your fork with upstream using bot you need to to enable [Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) option in the PR. 
    - Another possible reason for failure can due to the fork being in an organisation and not under a user.
    - The fork is located in an organization, not under your personal profile.
    - There is a conflict in the PR. Please resolve the conflict and try again.

**Comment by ash17290** [comment]
@ash17290 The updation of PR has failed. It can be due to one of the following reasons:
    - I don't have permissions to update this PR. To update your fork with upstream using bot you need to to enable [Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) option in the PR. 
    - Another possible reason for failure can due to the fork being in an organisation and not under a user.
    - The fork is located in an organization, not under your personal profile.
    - There is a conflict in the PR. Please resolve the conflict and try again.

**Comment by Shurtu-gal** [comment]
Closing as not needed anymore.

**Pull request closed without merging**
